title: Informática Ambiental
description: Proyecto colaborativo sobre sostenibilidad tecnológica.
theme: jekyll-theme-minimal # Puedes cambiarlo por el nombre del tema elegido
show_downloads: false
google_analytics:
